CREATE TABLE IF NOT EXISTS servers (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    url VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    icon TEXT,
    alias VARCHAR(255),
    added_at DATETIME NOT NULL,
    testing BOOLEAN NOT NULL DEFAULT FALSE,
    connected BOOLEAN NOT NULL DEFAULT FALSE,
    healthy BOOLEAN NOT NULL DEFAULT FALSE
);