//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
/// Copyright 2025 Miku Push! Team
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
use sea_orm::entity::prelude::*;
use mikupush_common::Upload;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upload")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub size: i64,
    pub mime_type: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    pub created_at: DateTime,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for Upload {
    fn from(model: Model) -> Self {
        Self {
            id: model.id,
            name: model.name,
            size: model.size as u64,
            mime_type: model.mime_type,
            path: model.path,
            url: model.url,
            created_at: model.created_at.and_utc(),
            status: model.status.into(),
        }
    }
}

impl From<Upload> for Model {
    fn from(model: Upload) -> Self {
        Self {
            id: model.id,
            name: model.name,
            size: model.size as i64,
            mime_type: model.mime_type,
            path: model.path,
            url: model.url,
            created_at: model.created_at.naive_utc(),
            status: model.status.to_string(),
        }
    }
}
