//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use mikupush_common::Upload;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upload")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub size: i64,
    pub mime_type: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
    pub created_at: DateTime,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl From<Model> for Upload {
    fn from(model: Model) -> Self {
        Self {
            id: model.id,
            name: model.name,
            size: model.size as u64,
            mime_type: model.mime_type,
            path: model.path,
            url: model.url,
            created_at: model.created_at.and_utc(),
            status: model.status.into(),
        }
    }
}

impl From<Upload> for Model {
    fn from(model: Upload) -> Self {
        Self {
            id: model.id,
            name: model.name,
            size: model.size as i64,
            mime_type: model.mime_type,
            path: model.path,
            url: model.url,
            created_at: model.created_at.naive_utc(),
            status: model.status.to_string(),
        }
    }
}
